-- DROP the tables and constraints
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS tours;

-- create the users table, it depends on no other
CREATE TABLE users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  f_name TEXT NOT NULL,
  l_name TEXT NOT NULL,
  email TEXT NOT NULL,
  password varchar NOT NULL,
  confirm_password varchar NOT NULL,
);

-- create the tours table without the foreign key
CREATE TABLE tours (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tour_name TEXT NOT NULL,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  description TEXT NOT NULL,
  max_tourists INTEGER,
  img varchar,
  policies TEXT NOT NULL,
  guide_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  posted TIMESTAMP DEFAULT NOW()
);
